---
apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  labels:
    run: frontend
spec:
  ports:
    - name: frontend
      protocol: TCP
      port: 443
      targetPort: 3000
  selector:
    app: frontend
